import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { 
  Printer, 
  ArrowLeft, 
  Download, 
  Truck, 
  Building2, 
  MapPin,
  Barcode,
  CheckCircle2
} from 'lucide-react';

export default function EWayBillPrint({ ewbId, onBack }) {
  const [ewb, setEwb] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchEwbDetails();
  }, [ewbId]);

  const fetchEwbDetails = async () => {
    try {
      setLoading(true);
      const res = await axios.get(`/api/eway-bills/${ewbId}`);
      setEwb(res.data);
    } catch (err) {
      alert('Failed to load E-Way Bill: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadJson = () => {
    window.open(`/api/eway-bills/${ewbId}/json`, '_blank');
  };

  const formatCurrency = (val) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 2
    }).format(val || 0);
  };

  if (loading || !ewb) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-sky-600"></div>
      </div>
    );
  }

  const company = ewb.company || {};

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      {/* Top Action Bar */}
      <div className="no-print bg-slate-900 text-white p-4 rounded-2xl shadow-lg flex flex-wrap items-center justify-between gap-4">
        <button
          onClick={onBack}
          className="px-3.5 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-xl transition flex items-center gap-1.5"
        >
          <ArrowLeft className="w-4 h-4" /> Back to E-Way Bills
        </button>

        <div className="flex items-center gap-2">
          <button
            onClick={handleDownloadJson}
            className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-xl transition shadow-sm flex items-center gap-1.5"
          >
            <Download className="w-4 h-4" /> Download GST Portal JSON
          </button>

          <button
            onClick={handlePrint}
            className="px-5 py-2 bg-sky-500 hover:bg-sky-400 text-slate-950 font-bold text-xs rounded-xl transition shadow-md flex items-center gap-1.5"
          >
            <Printer className="w-4 h-4" /> Print E-Way Bill Slip
          </button>
        </div>
      </div>

      {/* Printable E-Way Bill Sheet (A4 format) */}
      <div className="print-area bg-white p-8 rounded-2xl border-2 border-slate-900 shadow-xl text-slate-900 font-sans">
        
        {/* Top Title Banner */}
        <div className="flex items-center justify-between border-b-2 border-slate-900 pb-4 mb-4">
          <div>
            <span className="text-[10px] font-black tracking-widest text-sky-700 uppercase block">GOVERNMENT OF INDIA - GST E-WAY BILL SYSTEM</span>
            <h1 className="text-xl font-black text-slate-900 tracking-wide uppercase">
              e-Way Bill Details Slip (PART-A & PART-B)
            </h1>
          </div>

          <div className="text-right border border-slate-300 p-2 rounded bg-slate-50">
            <Barcode className="w-24 h-8 text-slate-800 mx-auto" />
            <span className="text-[10px] font-mono font-bold block text-slate-900 mt-1">{ewb.eway_bill_number}</span>
          </div>
        </div>

        {/* E-Way Bill Header Meta */}
        <div className="grid grid-cols-3 gap-4 bg-slate-100 p-3 rounded-lg border border-slate-300 text-xs font-mono mb-4">
          <div>
            <span className="text-slate-500 text-[10px] block">e-Way Bill No:</span>
            <strong className="text-sm text-sky-800">{ewb.eway_bill_number}</strong>
          </div>
          <div>
            <span className="text-slate-500 text-[10px] block">Generated Date:</span>
            <strong>{ewb.created_at ? ewb.created_at.split(' ')[0] : ewb.doc_date}</strong>
          </div>
          <div className="text-right">
            <span className="text-slate-500 text-[10px] block">Generated By:</span>
            <strong>{company.gstin} ({company.name})</strong>
          </div>
        </div>

        {/* PART A: Document & Party Details */}
        <div className="border border-slate-300 rounded-lg overflow-hidden mb-4 text-xs">
          <div className="bg-slate-900 text-white font-bold px-3 py-1.5 text-xs uppercase tracking-wider">
            PART - A: GOODS & TRANSACTION DETAILS
          </div>

          <div className="grid grid-cols-2 divide-x divide-slate-300 border-b border-slate-300 p-3">
            {/* Consignor */}
            <div className="space-y-1 pr-3">
              <span className="text-[10px] font-bold text-slate-500 uppercase block">FROM (CONSIGNOR):</span>
              <h4 className="font-bold text-slate-900">{company.name}</h4>
              <p className="font-mono font-bold text-slate-800">GSTIN: {company.gstin}</p>
              <p className="text-slate-600 text-[11px] whitespace-pre-line">{company.address}</p>
              <p className="font-mono font-semibold text-slate-700">Pincode: {ewb.from_pincode || '382330'}</p>
            </div>

            {/* Consignee */}
            <div className="space-y-1 pl-3">
              <span className="text-[10px] font-bold text-slate-500 uppercase block">TO (CONSIGNEE):</span>
              <h4 className="font-bold text-slate-900">{ewb.customer_name}</h4>
              <p className="font-mono font-bold text-slate-800">GSTIN: {ewb.customer_gstin || 'URP'}</p>
              <p className="text-slate-600 text-[11px] whitespace-pre-line">{ewb.customer_address}</p>
              <p className="font-mono font-semibold text-slate-700">Pincode: {ewb.to_pincode || '380001'}</p>
            </div>
          </div>

          <div className="grid grid-cols-4 p-3 bg-slate-50 text-[11px] gap-2">
            <div>
              <span className="text-slate-500 block">Doc Type:</span>
              <strong className="text-slate-900">{ewb.doc_type}</strong>
            </div>
            <div>
              <span className="text-slate-500 block">Doc Number:</span>
              <strong className="font-mono text-slate-900">{ewb.doc_number}</strong>
            </div>
            <div>
              <span className="text-slate-500 block">Doc Date:</span>
              <strong className="font-mono text-slate-900">{ewb.doc_date}</strong>
            </div>
            <div className="text-right">
              <span className="text-slate-500 block">Total Goods Value:</span>
              <strong className="text-sm font-mono text-slate-900">{formatCurrency(ewb.total_value)}</strong>
            </div>
          </div>
        </div>

        {/* Item Table */}
        <div className="border border-slate-300 rounded-lg overflow-hidden mb-4">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-200 text-slate-800 font-bold uppercase text-[10px] border-b border-slate-300">
              <tr>
                <th className="py-2 px-3">HSN Code</th>
                <th className="py-2 px-3">Item Description</th>
                <th className="py-2 px-3 text-center">Qty</th>
                <th className="py-2 px-3 text-right">Taxable Value (₹)</th>
                <th className="py-2 px-3 text-center">GST Rate</th>
                <th className="py-2 px-3 text-right">Total Amount (₹)</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 text-[11px]">
              {ewb.items && ewb.items.map((it, idx) => (
                <tr key={idx}>
                  <td className="py-2 px-3 font-mono font-semibold text-slate-700">{it.hsn_sac || '-'}</td>
                  <td className="py-2 px-3 font-medium text-slate-900">{it.description}</td>
                  <td className="py-2 px-3 text-center font-bold">{it.qty} {it.unit}</td>
                  <td className="py-2 px-3 text-right font-mono">{it.taxable_amount.toFixed(2)}</td>
                  <td className="py-2 px-3 text-center font-bold">{it.gst_rate}%</td>
                  <td className="py-2 px-3 text-right font-mono font-bold">{it.total_amount.toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* PART B: Transportation Details */}
        <div className="border border-slate-300 rounded-lg overflow-hidden mb-6 text-xs">
          <div className="bg-slate-900 text-white font-bold px-3 py-1.5 text-xs uppercase tracking-wider flex items-center justify-between">
            <span>PART - B: TRANSPORTATION & VEHICLE DETAILS</span>
            <Truck className="w-4 h-4" />
          </div>

          <div className="grid grid-cols-3 gap-4 p-3 font-mono text-[11px]">
            <div>
              <span className="text-slate-500 text-[10px] block">Mode of Transport:</span>
              <strong className="text-slate-900">{ewb.transport_mode}</strong>
            </div>
            <div>
              <span className="text-slate-500 text-[10px] block">Vehicle Number:</span>
              <strong className="text-sm text-amber-700 font-extrabold bg-amber-50 px-2 py-0.5 rounded border border-amber-300 inline-block">
                {ewb.vehicle_number}
              </strong>
            </div>
            <div>
              <span className="text-slate-500 text-[10px] block">Approx Distance:</span>
              <strong className="text-slate-900">{ewb.distance_km} KM</strong>
            </div>

            <div>
              <span className="text-slate-500 text-[10px] block">Transporter Name:</span>
              <strong className="text-slate-900">{ewb.transporter_name || 'Self Transport'}</strong>
            </div>
            <div>
              <span className="text-slate-500 text-[10px] block">Transporter ID:</span>
              <strong className="text-slate-900">{ewb.transporter_id || '-'}</strong>
            </div>
            <div>
              <span className="text-slate-500 text-[10px] block">LR / GR Doc No & Date:</span>
              <strong className="text-slate-900">{ewb.lr_rr_number ? `${ewb.lr_rr_number} (${ewb.lr_rr_date || ''})` : '-'}</strong>
            </div>
          </div>
        </div>

        {/* Footer Signatures */}
        <div className="flex items-end justify-between border-t border-slate-300 pt-6 text-xs">
          <div>
            <p className="text-slate-500 text-[10px]">E-Way Bill generated via DK Enterprise Billing Software.</p>
            <p className="text-slate-400 text-[10px]">Compliant with CGST/SGST Rules.</p>
          </div>

          <div className="text-center font-semibold">
            <p className="text-slate-900 font-bold mb-8">For {company.name || 'DK Enterprise'}</p>
            <div className="border-t border-slate-400 pt-1 px-8 text-slate-600 text-[10px]">
              Authorized Signatory
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
